### ISSUE TITLE
Request: Adding Depth to ConvertTo-Json statement and use regex more consistently

### ISSUE THREAD

**Issue by SjoerdV** [andlin03/EasyGraph#1]
First off, great module! I really like the 'open' nature of it. I have a few minor suggestions.

Could this block 
https://github.com/andlin03/EasyGraph/blob/7c40784e11ddbdd15769a2e02271ccabee2241fb/Public/Invoke-EasyGraphRequest.ps1#L105-L108
be altered into
```powershell
        if ($ContentType -match '^application/json' -and $Body) {
            $Body = $Body | ConvertTo-Json -Depth 100
            $Body = [System.Text.Encoding]::UTF8.GetBytes($Body)
        }
```
1. Adding a 'Depth' parameter would be prudent because the default value is only 2 (or maybe 10, but might still be too low to use the deeply nested 'sitePages' API efficiently)
2. Using regex is more consistent as it is also used here:
https://github.com/andlin03/EasyGraph/blob/7c40784e11ddbdd15769a2e02271ccabee2241fb/Public/Invoke-EasyGraphRequest.ps1#L140-L147

3. changing line 141 to read
```powershell
                    '^application/json' {
```
would also be nice, to be inline with (2)

**Comment by andlin03** [comment]
Request reviewed, testing shows that ConvertFrom-Json Depth parameter is a PowerShell 6.2 feature. Impelenting this would break PowerShell 5.1 compatibility. The default value of this parameter is 1024, therefore this part of the request is rejected.

**Comment by SjoerdV** [comment]
> Request reviewed, testing shows that ConvertFrom-Json Depth parameter is a PowerShell 6.2 feature. Impelenting this would break PowerShell 5.1 compatibility. The default value of this parameter is 1024, therefore this part of the request is rejected. 

Great Stuff! Thanks for your efforts! 

The code change proposal was actually about the `ConvertTo-Json` cmdlet (which has a default depth of 2)
This is different than the `ConvertFrom-Json` cmdlet.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-7.3#parameters

Depth parameter for `ConvertTo-Json` should also be available for PS5.1 (same default)

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-5.1#parameters
